### ISSUE TITLE
display result 

### ISSUE THREAD

**Issue by mikadev** [mtxr/SQLTools#32]
i'm trying to use the plugin but nothing displayed i see in console the command run but nothing happen i try all the parameters this is a bug ?

**Comment by mtxr** [comment]
Could you send me your console messages? Usually if it happens and you followed the docs, restart sublime solves it.

**Comment by mikadev** [comment]
Befor i write something here i usally do many test so i restart even reinstall sublim.
Here the console messages:
`SQLTools v0.5.3: Query: 
SQLTools v0.5.3: Usgin cli args C:/wamp/bin/mysql/mysql5.7.11/bin/mysql.exe -f --table -h127.0.0.1 -P3306 -uroot -p -Ddb_test`

i have also try all options here my conf:
`{
    "cli": {
        "mysql": "C:/mysql/mysql5.7.11/bin/mysql.exe"
    },
    "show_result_on_window": true
}`

**Comment by mtxr** [comment]
Show me the console output when you try to use the describe command table, please.

**Comment by rustam-crunch** [comment]
@mikadev 
1. Select part of SQL you want run
2. Ctrl+Shift+P -> ST:Execute

**Comment by mikadev** [comment]
@mxtr i already show you here the same
`SQLTools v0.5.3: Query: select * from test where 1
SQLTools v0.5.3: Usgin cli args C:/mysql/mysql5.7.11/bin/mysql.exe -f --table -h127.0.0.1 -P3306 -uroot -p -Ddb_test`
@rustam-crunch thanks but i know all of this there is no bug the command is executed as i explain but nothing displayed like in the demo page

**Comment by mtxr** [comment]
Could you try the new version?

**Comment by mikadev** [comment]
Done python error
`TypeError: object of type 'NoneType' has no len()`

**Comment by mtxr** [comment]
Same as #45 .

Fixed!

**Comment by mikadev** [comment]
still not working always say 'your databases has no table'...

**Comment by aditya43** [comment]
I'm having same issue,
I created table by writing query in the same window, then inserted records into it. Now when I try shortcuts for view TABLE SCHEMA (CTRL+e, CTRL+d) or show TABLE RECORDS (CTRL+e, CTRL+s), it says your database has no tables. 
However, if I write (SHOW TABLES) or (SELECT * FROM my_table) and then press (CTRL+e, CTRL+e) it does give me valid output.

Here is a screenshot : [https://ibb.co/cTo6Zb](url)

BTW, this is a great plugin. Really a time saver.

**Comment by tkopets** [comment]
@aditya43 
The list of tables is not refreshed after each SQL command you execute (`ST: Execute` or `CTRL+e, CTRL+e`).
Right now you can select the same connection again with `ST: Select Connection` and SQLTools will reload the list of available tables.
I'm not sure, but maybe we should reload the list of tables and columns after each `ST: Execute`,
 but that might be costly for remote or slow network connections.
